version: "3.8"

services:
  mediasoup:
    build: ./backend
    ports:
      - 3333:3333
    develop:
      watch:
        - path: ./backend
          target: /opt/app
          action: sync
        - path: ./backend/package.json
          action: rebuild
  nuxt:
    build: ./frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - path: ./frontend
          target: /opt/app
          action: sync
        - path: ./frontend/package.json
          action: rebuild
    depends_on:
      - mediasoup
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mediasoup
      - nuxt

