@startuml ERD

entity Pod {
    * podRef : string
    --
    * name : string
    * leader : string
    * meetingTime : Date
}

entity Customer {
    * customerRef : string
    --
    * podRef : string
    * firstName : string
    * lastName : string
    * email : string
    * netWorth: number
    * admin : boolean
}

entity Meeting {
    * meetingRef : string
    --
    * podRef : string
    * startTime : Date
    * endTime : Date
    * timeZone: string
    * vimeoId : string
    * roomId : string
    * roomCode : string
}

Customer }|--|| Pod
Meeting }o--|| Pod

@enduml